[package]
name = "dcli"
version = "0.1.0"
authors = ["murga"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
serenity = { default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
clap = "3.0.0-beta.2"
dirs = "3.0.1"
