[package]
name = "dcli"
version = "0.1.0"
authors = ["murga <motiurga@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10"
clap = "3.0.0-beta.2"
dirs = "3.0.1"
